workflows:
  ios-workflow:
    name: swiftful-thinking-17
    environment:
      xcode: 14.3.1  
    scripts:
      - name: Running tests
        script: |
          xcodebuild test \
            -project "Swiftful-thinking-17.xcodeproj" \
            -scheme "Swiftful-thinking-17" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
      - name: Building IPA for distribution
        script: |
          xcode-project build-ipa \
            --project "Swiftful-thinking-17.xcodeproj" \
            --scheme "Swiftful-thinking-17"
    artifacts:
      - build/ios/ipa/*.ipa
